
    CREATE OR REPLACE TABLE INTELLIGENCE_DEV.AI_CENTRE_FEATURE_STORE.OBSERVATIONS_CLEAN AS
    SELECT *
    FROM (
        SELECT * FROM INTELLIGENCE_DEV.AI_CENTRE_OBSERVATION_STAGING_TABLES.hba1c_VALUE_CUTOFFS
			UNION ALL

        SELECT * FROM INTELLIGENCE_DEV.AI_CENTRE_OBSERVATION_STAGING_TABLES.haemoglobin_VALUE_CUTOFFS
    ) ;
    