SELECT a.*
FROM INTELLIGENCE_DEV.AI_CENTRE_FEATURE_STORE.PATIENTS_WITH_2_HBA1C_GREATER_THAN_EQUAL_TO_48_V1 AS a
LEFT JOIN INTELLIGENCE_DEV.AI_CENTRE_FEATURE_STORE.PATIENTS_WITH_NON_T1DM_CODES_V1 AS b
  ON a.person_id = b.person_id  -- or another appropriate join condition
WHERE b.person_id IS NULL;