SELECT
    SNOMED_CODE AS CONCEPT_CODE,
    SNOMED_DESCRIPTION AS CONCEPT_NAME,
    COUNT(*) AS CONCEPT_COUNT,
    'SNOMED' AS VOCABULARY,
    'SUS_ECDS' AS CONCEPT_TYPE
FROM (
    SELECT
        EMERGENCY_CARE_PRIMARY_DIAGNOSIS_SNOMED AS SNOMED_CODE,
        EMERGENCY_CARE_PRIMARY_DIAGNOSIS AS SNOMED_DESCRIPTION
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.ECDS_EMERGENCY_CARE
    WHERE EMERGENCY_CARE_PRIMARY_DIAGNOSIS_SNOMED IS NOT NULL

    UNION ALL

    SELECT
        EMERGENCY_CARE_CHIEF_COMPLAINT_SNOMED_CT AS SNOMED_CODE,
        EMERGENCY_CARE_CHIEF_COMPLAINT_SNOMED_DESCRIPTION AS SNOMED_DESCRIPTION
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.ECDS_EMERGENCY_CARE
    WHERE EMERGENCY_CARE_CHIEF_COMPLAINT_SNOMED_CT IS NOT NULL

    UNION ALL

    SELECT
        EMERGENCY_CARE_PRIMARY_INVESTIGATION_SNOMED AS SNOMED_CODE,
        EMERGENCY_CARE_PRIMARY_INVESTIGATION AS SNOMED_DESCRIPTION
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.ECDS_EMERGENCY_CARE
    WHERE EMERGENCY_CARE_PRIMARY_INVESTIGATION_SNOMED IS NOT NULL

    UNION ALL

    SELECT
        EMERGENCY_CARE_PRIMARY_TREATMENT AS SNOMED_CODE,
        EMERGENCY_CARE_PRIMARY_TREATMENT_DESCRIPTION AS SNOMED_DESCRIPTION
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.ECDS_EMERGENCY_CARE
    WHERE EMERGENCY_CARE_PRIMARY_TREATMENT IS NOT NULL
) AS all_snomed_concepts
WHERE SNOMED_CODE IS NOT NULL
GROUP BY SNOMED_CODE, SNOMED_DESCRIPTION
ORDER BY CONCEPT_COUNT DESC