SELECT
    DIAGNOSIS_CODE AS CONCEPT_CODE,
    DIAGNOSIS_NAME AS CONCEPT_NAME,
    COUNT(*) AS CONCEPT_COUNT,
    'ICD10' AS VOCABULARY,
    'SUS_APC' AS CONCEPT_TYPE
FROM (
    -- Primary diagnosis
    SELECT
        PRIMARY_DIAGNOSIS_CODE AS DIAGNOSIS_CODE,
        PRIMARY_DIAGNOSIS AS DIAGNOSIS_NAME
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE PRIMARY_DIAGNOSIS_CODE IS NOT NULL

    UNION ALL

    -- Secondary diagnoses
    SELECT
        SECONDARY_DIAGNOSIS_CODE_1 AS DIAGNOSIS_CODE,
        SECONDARY_DIAGNOSIS_1 AS DIAGNOSIS_NAME
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_DIAGNOSIS_CODE_1 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_DIAGNOSIS_CODE_2 AS DIAGNOSIS_CODE,
        SECONDARY_DIAGNOSIS_2 AS DIAGNOSIS_NAME
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_DIAGNOSIS_CODE_2 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_DIAGNOSIS_CODE_3 AS DIAGNOSIS_CODE,
        SECONDARY_DIAGNOSIS_3 AS DIAGNOSIS_NAME
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_DIAGNOSIS_CODE_3 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_DIAGNOSIS_CODE_4 AS DIAGNOSIS_CODE,
        SECONDARY_DIAGNOSIS_4 AS DIAGNOSIS_NAME
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_DIAGNOSIS_CODE_4 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_DIAGNOSIS_CODE_5 AS DIAGNOSIS_CODE,
        SECONDARY_DIAGNOSIS_5 AS DIAGNOSIS_NAME
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_DIAGNOSIS_CODE_5 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_DIAGNOSIS_CODE_6 AS DIAGNOSIS_CODE,
        SECONDARY_DIAGNOSIS_6 AS DIAGNOSIS_NAME
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_DIAGNOSIS_CODE_6 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_DIAGNOSIS_CODE_7 AS DIAGNOSIS_CODE,
        SECONDARY_DIAGNOSIS_7 AS DIAGNOSIS_NAME
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_DIAGNOSIS_CODE_7 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_DIAGNOSIS_CODE_8 AS DIAGNOSIS_CODE,
        SECONDARY_DIAGNOSIS_8 AS DIAGNOSIS_NAME
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_DIAGNOSIS_CODE_8 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_DIAGNOSIS_CODE_9 AS DIAGNOSIS_CODE,
        SECONDARY_DIAGNOSIS_9 AS DIAGNOSIS_NAME
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_DIAGNOSIS_CODE_9 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_DIAGNOSIS_CODE_10 AS DIAGNOSIS_CODE,
        SECONDARY_DIAGNOSIS_10 AS DIAGNOSIS_NAME
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_DIAGNOSIS_CODE_10 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_DIAGNOSIS_CODE_11 AS DIAGNOSIS_CODE,
        SECONDARY_DIAGNOSIS_11 AS DIAGNOSIS_NAME
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_DIAGNOSIS_CODE_11 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_DIAGNOSIS_CODE_12 AS DIAGNOSIS_CODE,
        SECONDARY_DIAGNOSIS_12 AS DIAGNOSIS_NAME
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_DIAGNOSIS_CODE_12 IS NOT NULL
) AS all_diagnoses

GROUP BY DIAGNOSIS_CODE, DIAGNOSIS_NAME
ORDER BY CONCEPT_COUNT DESC