SELECT
    DIAGNOSIS_CODE AS CONCEPT_CODE,
    DIAGNOSIS_NAME AS CONCEPT_NAME,
    COUNT(*) AS CONCEPT_COUNT,
    'ICD10' AS VOCABULARY,
    'SUS_APC' AS CONCEPT_TYPE,
    -- Length of stay statistics
    APPROX_PERCENTILE(SPELL_DISCHARGE_LENGTH_OF_HOSPITAL_STAY, 0.25) AS LQ_VALUE,
    APPROX_PERCENTILE(SPELL_DISCHARGE_LENGTH_OF_HOSPITAL_STAY, 0.5) AS MEDIAN_VALUE,
    APPROX_PERCENTILE(SPELL_DISCHARGE_LENGTH_OF_HOSPITAL_STAY, 0.75) AS UQ_VALUE,
    -- Empty values
    NULL AS PERCENT_HAS_RESULT_VALUE,
    NULL AS RESULT_UNITS_ARRAY,
    -- Age percentiles
    APPROX_PERCENTILE(PATIENT_AGE_AT_ACTIVITY, 0.25) AS LQ_AGE,
    APPROX_PERCENTILE(PATIENT_AGE_AT_ACTIVITY, 0.5) AS MEDIAN_AGE,
    APPROX_PERCENTILE(PATIENT_AGE_AT_ACTIVITY, 0.75) AS UQ_AGE,
    -- Year distribution as percentages
    (COUNT_IF(EXTRACT(YEAR FROM ADMISSION_DATE) IN (2015, 2016)) * 100.0 / NULLIF(COUNT(*), 0)) AS PCT_2015_2016,
    (COUNT_IF(EXTRACT(YEAR FROM ADMISSION_DATE) IN (2017, 2018)) * 100.0 / NULLIF(COUNT(*), 0)) AS PCT_2017_2018,
    (COUNT_IF(EXTRACT(YEAR FROM ADMISSION_DATE) IN (2019, 2020)) * 100.0 / NULLIF(COUNT(*), 0)) AS PCT_2019_2020,
    (COUNT_IF(EXTRACT(YEAR FROM ADMISSION_DATE) IN (2021, 2022)) * 100.0 / NULLIF(COUNT(*), 0)) AS PCT_2021_2022,
    (COUNT_IF(EXTRACT(YEAR FROM ADMISSION_DATE) IN (2023, 2024)) * 100.0 / NULLIF(COUNT(*), 0)) AS PCT_2023_2024
FROM (
    -- Primary diagnosis
    SELECT
        PRIMARY_DIAGNOSIS_CODE AS DIAGNOSIS_CODE,
        PRIMARY_DIAGNOSIS AS DIAGNOSIS_NAME,
        PATIENT_AGE_AT_ACTIVITY,
        SPELL_DISCHARGE_LENGTH_OF_HOSPITAL_STAY,
        ADMISSION_DATE
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE PRIMARY_DIAGNOSIS_CODE IS NOT NULL

    UNION ALL

    -- Secondary diagnoses
    SELECT
        SECONDARY_DIAGNOSIS_CODE_1 AS DIAGNOSIS_CODE,
        SECONDARY_DIAGNOSIS_1 AS DIAGNOSIS_NAME,
        PATIENT_AGE_AT_ACTIVITY,
        SPELL_DISCHARGE_LENGTH_OF_HOSPITAL_STAY,
        ADMISSION_DATE
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_DIAGNOSIS_CODE_1 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_DIAGNOSIS_CODE_2 AS DIAGNOSIS_CODE,
        SECONDARY_DIAGNOSIS_2 AS DIAGNOSIS_NAME,
        PATIENT_AGE_AT_ACTIVITY,
        SPELL_DISCHARGE_LENGTH_OF_HOSPITAL_STAY,
        ADMISSION_DATE
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_DIAGNOSIS_CODE_2 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_DIAGNOSIS_CODE_3 AS DIAGNOSIS_CODE,
        SECONDARY_DIAGNOSIS_3 AS DIAGNOSIS_NAME,
        PATIENT_AGE_AT_ACTIVITY,
        SPELL_DISCHARGE_LENGTH_OF_HOSPITAL_STAY,
        ADMISSION_DATE
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_DIAGNOSIS_CODE_3 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_DIAGNOSIS_CODE_4 AS DIAGNOSIS_CODE,
        SECONDARY_DIAGNOSIS_4 AS DIAGNOSIS_NAME,
        PATIENT_AGE_AT_ACTIVITY,
        SPELL_DISCHARGE_LENGTH_OF_HOSPITAL_STAY,
        ADMISSION_DATE
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_DIAGNOSIS_CODE_4 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_DIAGNOSIS_CODE_5 AS DIAGNOSIS_CODE,
        SECONDARY_DIAGNOSIS_5 AS DIAGNOSIS_NAME,
        PATIENT_AGE_AT_ACTIVITY,
        SPELL_DISCHARGE_LENGTH_OF_HOSPITAL_STAY,
        ADMISSION_DATE
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_DIAGNOSIS_CODE_5 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_DIAGNOSIS_CODE_6 AS DIAGNOSIS_CODE,
        SECONDARY_DIAGNOSIS_6 AS DIAGNOSIS_NAME,
        PATIENT_AGE_AT_ACTIVITY,
        SPELL_DISCHARGE_LENGTH_OF_HOSPITAL_STAY,
        ADMISSION_DATE
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_DIAGNOSIS_CODE_6 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_DIAGNOSIS_CODE_7 AS DIAGNOSIS_CODE,
        SECONDARY_DIAGNOSIS_7 AS DIAGNOSIS_NAME,
        PATIENT_AGE_AT_ACTIVITY,
        SPELL_DISCHARGE_LENGTH_OF_HOSPITAL_STAY,
        ADMISSION_DATE
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_DIAGNOSIS_CODE_7 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_DIAGNOSIS_CODE_8 AS DIAGNOSIS_CODE,
        SECONDARY_DIAGNOSIS_8 AS DIAGNOSIS_NAME,
        PATIENT_AGE_AT_ACTIVITY,
        SPELL_DISCHARGE_LENGTH_OF_HOSPITAL_STAY,
        ADMISSION_DATE
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_DIAGNOSIS_CODE_8 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_DIAGNOSIS_CODE_9 AS DIAGNOSIS_CODE,
        SECONDARY_DIAGNOSIS_9 AS DIAGNOSIS_NAME,
        PATIENT_AGE_AT_ACTIVITY,
        SPELL_DISCHARGE_LENGTH_OF_HOSPITAL_STAY,
        ADMISSION_DATE
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_DIAGNOSIS_CODE_9 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_DIAGNOSIS_CODE_10 AS DIAGNOSIS_CODE,
        SECONDARY_DIAGNOSIS_10 AS DIAGNOSIS_NAME,
        PATIENT_AGE_AT_ACTIVITY,
        SPELL_DISCHARGE_LENGTH_OF_HOSPITAL_STAY,
        ADMISSION_DATE
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_DIAGNOSIS_CODE_10 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_DIAGNOSIS_CODE_11 AS DIAGNOSIS_CODE,
        SECONDARY_DIAGNOSIS_11 AS DIAGNOSIS_NAME,
        PATIENT_AGE_AT_ACTIVITY,
        SPELL_DISCHARGE_LENGTH_OF_HOSPITAL_STAY,
        ADMISSION_DATE
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_DIAGNOSIS_CODE_11 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_DIAGNOSIS_CODE_12 AS DIAGNOSIS_CODE,
        SECONDARY_DIAGNOSIS_12 AS DIAGNOSIS_NAME,
        PATIENT_AGE_AT_ACTIVITY,
        SPELL_DISCHARGE_LENGTH_OF_HOSPITAL_STAY,
        ADMISSION_DATE
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_DIAGNOSIS_CODE_12 IS NOT NULL
) AS all_diagnoses
GROUP BY DIAGNOSIS_CODE, DIAGNOSIS_NAME
ORDER BY CONCEPT_COUNT DESC;