SELECT c.NAME AS CONCEPT_NAME, c.CODE AS CONCEPT_CODE,
       COUNT(*) AS CONCEPT_COUNT, 'OBSERVATION' AS CONCEPT_TYPE,
       c.SCHEME_NAME AS VOCABULARY
FROM PROD_DWH.ANALYST_PRIMARY_CARE.OBSERVATION o
LEFT JOIN PROD_DWH.ANALYST_PRIMARY_CARE.CONCEPT c
ON o.CORE_CONCEPT_ID = c.DBID
GROUP BY c.NAME, c.CODE, c.SCHEME_NAME
ORDER BY CONCEPT_COUNT DESC