SELECT
    PROCEDURE_CODE AS CONCEPT_CODE,
    PROCEDURE_NAME AS CONCEPT_NAME,
    COUNT(*) AS CONCEPT_COUNT,
    'OPCS4' AS VOCABULARY,
    'SUS_APC_PROC' AS CONCEPT_TYPE,
    -- Length of stay statistics
    APPROX_PERCENTILE(SPELL_DISCHARGE_LENGTH_OF_HOSPITAL_STAY, 0.25) AS LQ_VALUE,
    APPROX_PERCENTILE(SPELL_DISCHARGE_LENGTH_OF_HOSPITAL_STAY, 0.5) AS MEDIAN_VALUE,
    APPROX_PERCENTILE(SPELL_DISCHARGE_LENGTH_OF_HOSPITAL_STAY, 0.75) AS UQ_VALUE,
    -- Empty values
    NULL AS PERCENT_HAS_RESULT_VALUE,
    NULL AS RESULT_UNITS_ARRAY,
    -- Age percentiles
    APPROX_PERCENTILE(PATIENT_AGE_AT_ACTIVITY, 0.25) AS LQ_AGE,
    APPROX_PERCENTILE(PATIENT_AGE_AT_ACTIVITY, 0.5) AS MEDIAN_AGE,
    APPROX_PERCENTILE(PATIENT_AGE_AT_ACTIVITY, 0.75) AS UQ_AGE,
    -- Year distribution as percentages
    (COUNT_IF(EXTRACT(YEAR FROM ADMISSION_DATE) IN (2015, 2016)) * 100.0 / NULLIF(COUNT(*), 0)) AS PCT_2015_2016,
    (COUNT_IF(EXTRACT(YEAR FROM ADMISSION_DATE) IN (2017, 2018)) * 100.0 / NULLIF(COUNT(*), 0)) AS PCT_2017_2018,
    (COUNT_IF(EXTRACT(YEAR FROM ADMISSION_DATE) IN (2019, 2020)) * 100.0 / NULLIF(COUNT(*), 0)) AS PCT_2019_2020,
    (COUNT_IF(EXTRACT(YEAR FROM ADMISSION_DATE) IN (2021, 2022)) * 100.0 / NULLIF(COUNT(*), 0)) AS PCT_2021_2022,
    (COUNT_IF(EXTRACT(YEAR FROM ADMISSION_DATE) IN (2023, 2024)) * 100.0 / NULLIF(COUNT(*), 0)) AS PCT_2023_2024
FROM (
    -- Primary procedure
    SELECT
        PRIMARY_PROCEDURE_CODE AS PROCEDURE_CODE,
        PRIMARY_PROCEDURE AS PROCEDURE_NAME,
        PATIENT_AGE_AT_ACTIVITY,
        SPELL_DISCHARGE_LENGTH_OF_HOSPITAL_STAY,
        ADMISSION_DATE
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE PRIMARY_PROCEDURE_CODE IS NOT NULL

    UNION ALL

    -- Secondary procedures
    SELECT
        SECONDARY_PROCEDURE_CODE_1 AS PROCEDURE_CODE,
        SECONDARY_PROCEDURE_1 AS PROCEDURE_NAME,
        PATIENT_AGE_AT_ACTIVITY,
        SPELL_DISCHARGE_LENGTH_OF_HOSPITAL_STAY,
        ADMISSION_DATE
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_PROCEDURE_CODE_1 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_PROCEDURE_CODE_2 AS PROCEDURE_CODE,
        SECONDARY_PROCEDURE_2 AS PROCEDURE_NAME,
        PATIENT_AGE_AT_ACTIVITY,
        SPELL_DISCHARGE_LENGTH_OF_HOSPITAL_STAY,
        ADMISSION_DATE
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_PROCEDURE_CODE_2 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_PROCEDURE_CODE_3 AS PROCEDURE_CODE,
        SECONDARY_PROCEDURE_3 AS PROCEDURE_NAME,
        PATIENT_AGE_AT_ACTIVITY,
        SPELL_DISCHARGE_LENGTH_OF_HOSPITAL_STAY,
        ADMISSION_DATE
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_PROCEDURE_CODE_3 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_PROCEDURE_CODE_4 AS PROCEDURE_CODE,
        SECONDARY_PROCEDURE_4 AS PROCEDURE_NAME,
        PATIENT_AGE_AT_ACTIVITY,
        SPELL_DISCHARGE_LENGTH_OF_HOSPITAL_STAY,
        ADMISSION_DATE
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_PROCEDURE_CODE_4 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_PROCEDURE_CODE_5 AS PROCEDURE_CODE,
        SECONDARY_PROCEDURE_5 AS PROCEDURE_NAME,
        PATIENT_AGE_AT_ACTIVITY,
        SPELL_DISCHARGE_LENGTH_OF_HOSPITAL_STAY,
        ADMISSION_DATE
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_PROCEDURE_CODE_5 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_PROCEDURE_CODE_6 AS PROCEDURE_CODE,
        SECONDARY_PROCEDURE_6 AS PROCEDURE_NAME,
        PATIENT_AGE_AT_ACTIVITY,
        SPELL_DISCHARGE_LENGTH_OF_HOSPITAL_STAY,
        ADMISSION_DATE
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_PROCEDURE_CODE_6 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_PROCEDURE_CODE_7 AS PROCEDURE_CODE,
        SECONDARY_PROCEDURE_7 AS PROCEDURE_NAME,
        PATIENT_AGE_AT_ACTIVITY,
        SPELL_DISCHARGE_LENGTH_OF_HOSPITAL_STAY,
        ADMISSION_DATE
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_PROCEDURE_CODE_7 IS NOT NULL

    UNION ALL
    SELECT
        SECONDARY_PROCEDURE_CODE_8 AS PROCEDURE_CODE,
        SECONDARY_PROCEDURE_8 AS PROCEDURE_NAME,
        PATIENT_AGE_AT_ACTIVITY,
        SPELL_DISCHARGE_LENGTH_OF_HOSPITAL_STAY,
        ADMISSION_DATE
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_PROCEDURE_CODE_8 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_PROCEDURE_CODE_9 AS PROCEDURE_CODE,
        SECONDARY_PROCEDURE_9 AS PROCEDURE_NAME,
        PATIENT_AGE_AT_ACTIVITY,
        SPELL_DISCHARGE_LENGTH_OF_HOSPITAL_STAY,
        ADMISSION_DATE
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_PROCEDURE_CODE_9 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_PROCEDURE_CODE_10 AS PROCEDURE_CODE,
        SECONDARY_PROCEDURE_10 AS PROCEDURE_NAME,
        PATIENT_AGE_AT_ACTIVITY,
        SPELL_DISCHARGE_LENGTH_OF_HOSPITAL_STAY,
        ADMISSION_DATE
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_PROCEDURE_CODE_10 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_PROCEDURE_CODE_11 AS PROCEDURE_CODE,
        SECONDARY_PROCEDURE_11 AS PROCEDURE_NAME,
        PATIENT_AGE_AT_ACTIVITY,
        SPELL_DISCHARGE_LENGTH_OF_HOSPITAL_STAY,
        ADMISSION_DATE
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_PROCEDURE_CODE_11 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_PROCEDURE_CODE_12 AS PROCEDURE_CODE,
        SECONDARY_PROCEDURE_12 AS PROCEDURE_NAME,
        PATIENT_AGE_AT_ACTIVITY,
        SPELL_DISCHARGE_LENGTH_OF_HOSPITAL_STAY,
        ADMISSION_DATE
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_PROCEDURE_CODE_12 IS NOT NULL
) AS all_procedures
GROUP BY PROCEDURE_CODE, PROCEDURE_NAME
ORDER BY CONCEPT_COUNT DESC;