SELECT
    PROCEDURE_CODE AS CONCEPT_CODE,
    PROCEDURE_NAME AS CONCEPT_NAME,
    COUNT(*) AS CONCEPT_COUNT,
    'OPCS-4' AS VOCABULARY,
    'SUS_APC_PROC' AS CONCEPT_TYPE
FROM (
    -- Primary procedure
    SELECT
        PRIMARY_PROCEDURE_CODE AS PROCEDURE_CODE,
        PRIMARY_PROCEDURE AS PROCEDURE_NAME
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE PRIMARY_PROCEDURE_CODE IS NOT NULL

    UNION ALL

    -- Secondary procedures
    SELECT
        SECONDARY_PROCEDURE_CODE_1 AS PROCEDURE_CODE,
        SECONDARY_PROCEDURE_1 AS PROCEDURE_NAME
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_PROCEDURE_CODE_1 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_PROCEDURE_CODE_2 AS PROCEDURE_CODE,
        SECONDARY_PROCEDURE_2 AS PROCEDURE_NAME
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_PROCEDURE_CODE_2 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_PROCEDURE_CODE_3 AS PROCEDURE_CODE,
        SECONDARY_PROCEDURE_3 AS PROCEDURE_NAME
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_PROCEDURE_CODE_3 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_PROCEDURE_CODE_4 AS PROCEDURE_CODE,
        SECONDARY_PROCEDURE_4 AS PROCEDURE_NAME
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_PROCEDURE_CODE_4 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_PROCEDURE_CODE_5 AS PROCEDURE_CODE,
        SECONDARY_PROCEDURE_5 AS PROCEDURE_NAME
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_PROCEDURE_CODE_5 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_PROCEDURE_CODE_6 AS PROCEDURE_CODE,
        SECONDARY_PROCEDURE_6 AS PROCEDURE_NAME
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_PROCEDURE_CODE_6 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_PROCEDURE_CODE_7 AS PROCEDURE_CODE,
        SECONDARY_PROCEDURE_7 AS PROCEDURE_NAME
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_PROCEDURE_CODE_7 IS NOT NULL

    UNION ALL
    SELECT
        SECONDARY_PROCEDURE_CODE_8 AS PROCEDURE_CODE,
        SECONDARY_PROCEDURE_8 AS PROCEDURE_NAME
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_PROCEDURE_CODE_8 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_PROCEDURE_CODE_9 AS PROCEDURE_CODE,
        SECONDARY_PROCEDURE_9 AS PROCEDURE_NAME
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_PROCEDURE_CODE_9 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_PROCEDURE_CODE_10 AS PROCEDURE_CODE,
        SECONDARY_PROCEDURE_10 AS PROCEDURE_NAME
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_PROCEDURE_CODE_10 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_PROCEDURE_CODE_11 AS PROCEDURE_CODE,
        SECONDARY_PROCEDURE_11 AS PROCEDURE_NAME
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_PROCEDURE_CODE_11 IS NOT NULL

    UNION ALL

    SELECT
        SECONDARY_PROCEDURE_CODE_12 AS PROCEDURE_CODE,
        SECONDARY_PROCEDURE_12 AS PROCEDURE_NAME
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.UNIFIED_SUS_ADMITTED_PATIENT_CARE
    WHERE SECONDARY_PROCEDURE_CODE_12 IS NOT NULL
) AS all_procedures
GROUP BY PROCEDURE_CODE, PROCEDURE_NAME
ORDER BY CONCEPT_COUNT DESC