# Maps Snowflake account IDs to ICB configuration prefixes
# This mapping is used to automatically determine which config file to load
# based on the current Snowflake account in config_utils.py
account_mappings:
  SE56186: nel_icb  # NEL ICB account
  ED64551: sel_icb  # SEL ICB account
  SK29378: ncl_icb  # NCL ICB account