icb_name: NEL
deployment:
  warehouse: INTELLIGENCE_XS
  database: INTELLIGENCE_DEV
  schema: AI_CENTRE_DEV
  app_title: PhenoLab
definition_library:
  database: INTELLIGENCE_DEV
  schema: AI_CENTRE_DEFINITION_LIBRARY
feature_store:
  database: INTELLIGENCE_DEV
  schema: AI_CENTRE_FEATURE_STORE
measurement_configs:
  database: INTELLIGENCE_DEV
  schema: AI_CENTRE_MEASUREMENT_CONFIGS
gp_observation_table: PROD_DWH.ANALYST_PRIMARY_CARE.OBSERVATION
gp_concept_table: PROD_DWH.ANALYST_PRIMARY_CARE.CONCEPT
gp_concept_map_table: PROD_DWH.ANALYST_PRIMARY_CARE.CONCEPT_MAP
# placeholders
sus_icd10_table: PLACEHOLDER_NOT_USED
sus_opcs4_table: PLACEHOLDER_NOT_USED