icb_name: NEL
deployment:
  warehouse: INTELLIGENCE_XS
  database: INTELLIGENCE_DEV
  schema: PHENOLAB_DEV
  app_title: PhenoLab_dev
definition_library:
  database: INTELLIGENCE_DEV
  schema: PHENOLAB_DEV
feature_store:
  database: INTELLIGENCE_DEV
  schema: PHENOLAB_DEV
measurement_configs:
  database: INTELLIGENCE_DEV
  schema: PHENOLAB_DEV
gp_observation_table: PROD_DWH.ANALYST_PRIMARY_CARE.OBSERVATION
gp_concept_table: PROD_DWH.ANALYST_PRIMARY_CARE.CONCEPT
gp_concept_map_table: PROD_DWH.ANALYST_PRIMARY_CARE.CONCEPT_MAP
# placeholders
sus_icd10_table: PLACEHOLDER_NOT_USED
sus_opcs4_table: PLACEHOLDER_NOT_USED
int_observation_table: DATA_LAB_AI_CENTRE.JZ_DEV.INT_OBSERVATION