icb_name: NEL
definition_library:
  database: INTELLIGENCE_DEV
  schema: PHENOLAB_DEV
feature_store:
  database: INTELLIGENCE_DEV
  schema: PHENOLAB_DEV
  metadata_schema: PHENOLAB_DEV
measurement_configs:
  database: INTELLIGENCE_DEV
  schema: PHENOLAB_DEV
gp_observation_table: PROD_DWH.ANALYST_PRIMARY_CARE.OBSERVATION