SELECT
    SNOMED_CODE AS CONCEPT_CODE,
    SNOMED_DESCRIPTION AS CONCEPT_NAME,
    COUNT(*) AS CONCEPT_COUNT,
    'SUS_ECDS' AS CONCEPT_TYPE,
    'SNOMED' AS VOCABULARY,
    -- Empty LQ_VALUE
    NULL AS LQ_VALUE,
    NULL AS MEDIAN_VALUE,
    NULL AS UQ_VALUE,
    -- Empty values
    NULL AS PERCENT_HAS_RESULT_VALUE,
    NULL AS RESULT_UNITS_ARRAY,
    -- Age percentiles
    APPROX_PERCENTILE(AGE_AT_CDS_ACTIVITY_DATE, 0.25) AS LQ_AGE,
    APPROX_PERCENTILE(AGE_AT_CDS_ACTIVITY_DATE, 0.5) AS MEDIAN_AGE,
    APPROX_PERCENTILE(AGE_AT_CDS_ACTIVITY_DATE, 0.75) AS UQ_AGE,
    -- Year distribution as percentages
    (COUNT_IF(EXTRACT(YEAR FROM EMERGENCY_CARE_ARRIVAL_DATE) IN (2015, 2016)) * 100.0 / NULLIF(COUNT(*), 0)) AS PCT_2015_2016,
    (COUNT_IF(EXTRACT(YEAR FROM EMERGENCY_CARE_ARRIVAL_DATE) IN (2017, 2018)) * 100.0 / NULLIF(COUNT(*), 0)) AS PCT_2017_2018,
    (COUNT_IF(EXTRACT(YEAR FROM EMERGENCY_CARE_ARRIVAL_DATE) IN (2019, 2020)) * 100.0 / NULLIF(COUNT(*), 0)) AS PCT_2019_2020,
    (COUNT_IF(EXTRACT(YEAR FROM EMERGENCY_CARE_ARRIVAL_DATE) IN (2021, 2022)) * 100.0 / NULLIF(COUNT(*), 0)) AS PCT_2021_2022,
    (COUNT_IF(EXTRACT(YEAR FROM EMERGENCY_CARE_ARRIVAL_DATE) IN (2023, 2024)) * 100.0 / NULLIF(COUNT(*), 0)) AS PCT_2023_2024
FROM (
    SELECT
        EMERGENCY_CARE_PRIMARY_DIAGNOSIS_SNOMED AS SNOMED_CODE,
        EMERGENCY_CARE_PRIMARY_DIAGNOSIS AS SNOMED_DESCRIPTION,
        AGE_AT_CDS_ACTIVITY_DATE,
        EMERGENCY_CARE_ARRIVAL_DATE
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.ECDS_EMERGENCY_CARE
    WHERE EMERGENCY_CARE_PRIMARY_DIAGNOSIS_SNOMED IS NOT NULL

    UNION ALL

    SELECT
        EMERGENCY_CARE_CHIEF_COMPLAINT_SNOMED_CT AS SNOMED_CODE,
        EMERGENCY_CARE_CHIEF_COMPLAINT_SNOMED_DESCRIPTION AS SNOMED_DESCRIPTION,
        AGE_AT_CDS_ACTIVITY_DATE,
        EMERGENCY_CARE_ARRIVAL_DATE
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.ECDS_EMERGENCY_CARE
    WHERE EMERGENCY_CARE_CHIEF_COMPLAINT_SNOMED_CT IS NOT NULL

    UNION ALL

    SELECT
        EMERGENCY_CARE_PRIMARY_INVESTIGATION_SNOMED AS SNOMED_CODE,
        EMERGENCY_CARE_PRIMARY_INVESTIGATION AS SNOMED_DESCRIPTION,
        AGE_AT_CDS_ACTIVITY_DATE,
        EMERGENCY_CARE_ARRIVAL_DATE
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.ECDS_EMERGENCY_CARE
    WHERE EMERGENCY_CARE_PRIMARY_INVESTIGATION_SNOMED IS NOT NULL

    UNION ALL

    SELECT
        EMERGENCY_CARE_PRIMARY_TREATMENT AS SNOMED_CODE,
        EMERGENCY_CARE_PRIMARY_TREATMENT_DESCRIPTION AS SNOMED_DESCRIPTION,
        AGE_AT_CDS_ACTIVITY_DATE,
        EMERGENCY_CARE_ARRIVAL_DATE
    FROM PROD_DWH.ANALYST_FACTS_UNIFIED_SUS.ECDS_EMERGENCY_CARE
    WHERE EMERGENCY_CARE_PRIMARY_TREATMENT IS NOT NULL
) AS all_snomed_concepts
WHERE SNOMED_CODE IS NOT NULL
GROUP BY SNOMED_CODE, SNOMED_DESCRIPTION
ORDER BY CONCEPT_COUNT DESC;