CREATE TABLE IF NOT EXISTS AI_CENTRE_PHENOTYPE_LIBRARY.HDRUK_PHENOTYPES(
    CONCEPT_CODE VARCHAR,
    CONCEPT_NAME VARCHAR,
    VOCABULARY VARCHAR,
    CODELIST_ID VARCHAR,
    CODELIST_NAME VARCHAR,
    CODELIST_VERSION VARCHAR,
    PHENOTYPE_ID VARCHAR,
    PHENOTYPE_NAME VARCHAR,
    PHENOTYPE_VERSION VARCHAR,
    PHENOTYPE_SOURCE VARCHAR,
    OMOP_CONCEPT_ID INTEGER,
    VERSION_DATETIME TIMESTAMP_NTZ,
    UPLOADED_DATETIME TIMESTAMP_NTZ
);