MERGE INTO HDRUK_PHENOTYPES target
USING TEMP_HDRUK_PHENOTYPES source
ON target.CONCEPT_CODE = source.CONCEPT_CODE
AND target.VOCABULARY = source.VOCABULARY
AND target.PHENOTYPE_VERSION = source.PHENOTYPE_VERSION
WHEN NOT MATCHED THEN
    INSERT (
        CONCEPT_CODE, CONCEPT_NAME, VOCABULARY,
        CODELIST_ID, CODELIST_NAME, CODELIST_VERSION,
        PHENOTYPE_ID, PHENOTYPE_NAME, PHENOTYPE_VERSION,
        PHENOTYPE_SOURCE, OMOP_CONCEPT_ID,
        VERSION_DATETIME, UPLOADED_DATETIME
    )
    VALUES (
        source.CONCEPT_CODE, source.CONCEPT_NAME, source.VOCABULARY,
        source.CODELIST_ID, source.CODELIST_NAME, source.CODELIST_VERSION,
        source.PHENOTYPE_ID, source.PHENOTYPE_NAME, source.PHENOTYPE_VERSION,
        source.PHENOTYPE_SOURCE, source.OMOP_CONCEPT_ID,
        source.VERSION_DATETIME, source.UPLOADED_DATETIME
    );