-- canonical phenotypes
CREATE TABLE IF NOT EXISTS PHENOTYPE_LOOKUP (
    PHENOTYPE_ID VARCHAR NOT NULL,
    PHENOTYPE_CODE INTEGER NOT NULL
    PHENOTYPE_NAME VARCHAR NOT NULL,
    PHENOTYPE_VOCABULARY VARCHAR NOT NULL,
    PHENOTYPE_DESC VARCHAR,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- disorder phenotypes
CREATE TABLE IF NOT EXISTS DISORDER_PHENOTYPES (
    PHENOTYPE_ID VARCHAR NOT NULL,
    PHENOTYPE_NAME VARCHAR NOT NULL,
    PHENOTYPE_SOURCE_NAME VARCHAR NOT NULL,    
    PHENOTYPE_SOURCE_CODE VARCHAR NOT NULL,
    CONCEPT_DBID INTEGER NOT NULL,
    CONCEPT_NAME VARCHAR NOT NULL, 
    CONCEPT_CODE VARCHAR NOT NULL,
    CONCEPT_VOCABULARY VARCHAR NOT NULL,
    CONCEPT_TYPE VARCHAR NOT NULL,
    CONCEPT_DESC TEXT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- observed phenotypes
-- outcome phenotypes
-- medication definitions
-- measurement definitions
