CREATE SCHEMA IF NOT EXISTS AI_CENTRE_PHENOTYPE_LIBRARY;

-- diagnosis reference table
-- requires a tempoerary megalith table to exist (SNOMED_UK_MEGALITH_TEMP)
CREATE OR REPLACE TABLE AI_CENTRE_PHENOTYPE_LIBRARY.SNOMED_UK_DIAGNOSIS_REFERENCE AS
SELECT 
    m.MEGALITH,
    m.URL,
    m.REFSET_NAME,
    m.REFSET_CODE,
    m.CONCEPT_NAME,
    m.CONCEPT_CODE,
    c.DBID
FROM AI_CENTRE_PHENOTYPE_LIBRARY.SNOMED_UK_MEGALITH_TEMP m
LEFT JOIN PROD_DWH.ANALYST_PRIMARY_CARE.CONCEPT c
    ON m.CONCEPT_CODE = c.CODE
    AND c.SCHEME = 71
WHERE m.REFSET_NAME ILIKE '%diagnoses simple reference set%';

-- drop temp table
DROP TABLE IF EXISTS AI_CENTRE_PHENOTYPE_LIBRARY.SNOMED_UK_MEGALITH_TEMP;