[snowflake]
account = "ATKJNCU-SOUTHEASTLONDON"
user = "JACK.BARKER@NHS.NET"
password = "YOUR_PASSWORD"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "DATA_LAB_AI_CENTRE"
schema = "PIPELINE_PROD"
